version: "3.2"
services:
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: 'rabbitmq'
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - /home/hbarbosa/Documentos/faculdade/distribuida/rabbit-volume/
    networks:
      - rabbitmq_go_net
  mongo:
    image: mongo
    restart: always
    container_name: 'mongodb'
    environment:
      MONGO_INITDB_DATABASE: rabbit
      MONGO_INITDB_ROOT_USERNAME: test
      MONGO_INITDB_ROOT_PASSWORD: senha
    volumes:
      - /home/hbarbosa/Documentos/faculdade/distribuida/mongo-volume/
    ports:
      - 27017:27017
networks:
  rabbitmq_go_net:
    driver: bridge